# Generated by Django 5.2.9 on 2025-12-27 08:38

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.CharField(max_length=10, unique=True, verbose_name='事業所コード')),
                ('location_name', models.CharField(max_length=100, verbose_name='事業所名')),
            ],
            options={
                'verbose_name': '事業所',
                'verbose_name_plural': '事業所',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_code', models.CharField(max_length=20, unique=True, verbose_name='利用者コード')),
                ('full_name', models.CharField(max_length=100, verbose_name='氏名')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='生年月日')),
                ('recipient_number', models.CharField(blank=True, max_length=20, verbose_name='受給者番号')),
                ('guardian_name', models.CharField(blank=True, max_length=100, verbose_name='保護者氏名')),
                ('guardian_email', models.EmailField(blank=True, max_length=254, verbose_name='保護者メールアドレス')),
                ('long_term_goal', models.TextField(blank=True, verbose_name='長期目標')),
                ('short_term_goal', models.TextField(blank=True, verbose_name='短期目標')),
                ('support_content', models.TextField(blank=True, verbose_name='支援内容')),
                ('guardian_signature', models.TextField(blank=True, verbose_name='保護者署名データ')),
                ('signature_date', models.DateTimeField(blank=True, null=True, verbose_name='署名日時')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='billing_management.servicelocation', verbose_name='所属事業所')),
            ],
            options={
                'verbose_name': '利用者',
                'verbose_name_plural': '利用者',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('super_admin', 'スーパー管理者'), ('location_admin', '事業所管理者'), ('staff', '一般スタッフ')], default='staff', max_length=20, verbose_name='役割')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing_management.servicelocation', verbose_name='所属事業所')),
            ],
            options={
                'verbose_name': 'ユーザー',
                'verbose_name_plural': 'ユーザー',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_code', models.CharField(max_length=20, unique=True, verbose_name='職員コード')),
                ('full_name', models.CharField(default='未設定', max_length=100, verbose_name='氏名')),
                ('is_specialist', models.BooleanField(default=False, verbose_name='専門職フラグ')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing_management.servicelocation', verbose_name='所属事業所')),
            ],
            options={
                'verbose_name': '職員',
                'verbose_name_plural': '職員',
            },
        ),
        migrations.CreateModel(
            name='StaffContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_start_date', models.DateField(verbose_name='契約開始日')),
                ('contract_hours_week', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='週契約時間（時間）')),
                ('is_permanent', models.BooleanField(default=False, verbose_name='常勤契約')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing_management.staff', verbose_name='職員')),
            ],
            options={
                'verbose_name': '職員契約',
                'verbose_name_plural': '職員契約',
            },
        ),
        migrations.CreateModel(
            name='FTESufficientStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_month', models.DateField(verbose_name='計算対象月（月初日）')),
                ('total_fte', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='全職員の合計FTE')),
                ('specialist_fte', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='専門職の合計FTE')),
                ('required_fte_for_kasan', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='加算に必要なFTE')),
                ('is_kasan_sufficient', models.BooleanField(default=False, verbose_name='加算充足ステータス')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing_management.servicelocation', verbose_name='事業所')),
            ],
            options={
                'verbose_name': '加算充足ステータス',
                'verbose_name_plural': '加算充足ステータス',
                'unique_together': {('location', 'calculation_month')},
            },
        ),
        migrations.CreateModel(
            name='ProgressAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateField(verbose_name='評価日')),
                ('progress_score', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='成長スコア（1-5段階）')),
                ('specialist_comment', models.TextField(blank=True, verbose_name='専門職コメント（PT/OT等）')),
                ('media_url', models.URLField(blank=True, verbose_name='画像・動画URL')),
                ('analysis_result_json', models.JSONField(blank=True, null=True, verbose_name='AI分析結果')),
                ('nlp_keyword_tags', models.CharField(blank=True, max_length=255, verbose_name='NLP抽出キーワード')),
                ('sentiment_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='感情スコア')),
                ('record_quality_score', models.IntegerField(blank=True, null=True, verbose_name='記録の質スコア (1-5)')),
                ('ai_feedback', models.TextField(blank=True, verbose_name='AI改善提案')),
                ('analyzed_at', models.DateTimeField(blank=True, null=True, verbose_name='AI分析日時')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing_management.client', verbose_name='利用者')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing_management.staff', verbose_name='担当職員')),
            ],
            options={
                'verbose_name': '進捗・評価',
                'verbose_name_plural': '進捗・評価',
                'unique_together': {('client', 'assessment_date')},
            },
        ),
        migrations.CreateModel(
            name='StaffPeerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField(auto_now_add=True, verbose_name='評価日')),
                ('cooperation_score', models.IntegerField(verbose_name='協調性スコア（1-5）')),
                ('review_comment', models.TextField(blank=True, verbose_name='コメント')),
                ('reviewed_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='billing_management.staff', verbose_name='評価対象者')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to='billing_management.staff', verbose_name='評価者')),
            ],
            options={
                'verbose_name': '職員相互評価',
                'verbose_name_plural': '職員相互評価',
                'unique_together': {('reviewer', 'reviewed_staff', 'review_date')},
            },
        ),
        migrations.CreateModel(
            name='WorkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(verbose_name='勤務日')),
                ('service_type', models.CharField(default='Hodei', max_length=10, verbose_name='サービス種別（放デイ/ミニリハなど）')),
                ('duration_minutes', models.IntegerField(verbose_name='勤務時間（分）')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing_management.staff', verbose_name='職員')),
            ],
            options={
                'verbose_name': '勤務実績',
                'verbose_name_plural': '勤務実績',
                'unique_together': {('staff', 'work_date', 'service_type')},
            },
        ),
    ]
