# Generated by Django 5.2.9 on 2025-12-09 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.CharField(max_length=10, unique=True, verbose_name='事業所コード')),
                ('location_name', models.CharField(max_length=100, verbose_name='事業所名')),
            ],
            options={
                'verbose_name': '事業所',
                'verbose_name_plural': '事業所',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_code', models.CharField(max_length=20, unique=True, verbose_name='職員コード')),
                ('full_name', models.CharField(default='未設定', max_length=100, verbose_name='氏名')),
                ('is_specialist', models.BooleanField(default=False, verbose_name='専門職フラグ')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing_management.servicelocation', verbose_name='所属事業所')),
            ],
            options={
                'verbose_name': '職員',
                'verbose_name_plural': '職員',
            },
        ),
        migrations.CreateModel(
            name='StaffContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_start_date', models.DateField(verbose_name='契約開始日')),
                ('contract_hours_week', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='週契約時間（時間）')),
                ('is_permanent', models.BooleanField(default=False, verbose_name='常勤契約')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing_management.staff', verbose_name='職員')),
            ],
            options={
                'verbose_name': '職員契約',
                'verbose_name_plural': '職員契約',
            },
        ),
        migrations.CreateModel(
            name='WorkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(verbose_name='勤務日')),
                ('duration_minutes', models.IntegerField(verbose_name='勤務時間（分）')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing_management.staff', verbose_name='職員')),
            ],
            options={
                'verbose_name': '勤務実績',
                'verbose_name_plural': '勤務実績',
                'unique_together': {('staff', 'work_date')},
            },
        ),
    ]
