# Generated by Django 5.2.9 on 2025-12-28 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='プロンプトの識別名（例: sentiment_analysis）', max_length=100, unique=True, verbose_name='プロンプト名')),
                ('display_name', models.CharField(help_text='管理画面での表示名', max_length=200, verbose_name='表示名')),
                ('description', models.TextField(blank=True, help_text='プロンプトの目的や使用方法', verbose_name='説明')),
                ('system_prompt', models.TextField(help_text='AIの役割や振る舞いを定義', verbose_name='システムプロンプト')),
                ('user_template', models.TextField(help_text='変数を含むテンプレート（例: {client_name}）', verbose_name='ユーザープロンプトテンプレート')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='バージョン')),
                ('is_active', models.BooleanField(default=True, help_text='このプロンプトを使用するか', verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prompts', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': 'AIプロンプト',
                'verbose_name_plural': 'AIプロンプト',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(help_text='google, openai, anthropic等', max_length=50, verbose_name='AIプロバイダー')),
                ('model', models.CharField(help_text='gemini-1.5-flash, gpt-4.1-mini等', max_length=100, verbose_name='モデル名')),
                ('task_type', models.CharField(choices=[('sentiment_analysis', '感情分析'), ('progress_record_generation', '進捗記録生成'), ('churn_risk_prediction', '離脱リスク予測'), ('other', 'その他')], max_length=50, verbose_name='タスクタイプ')),
                ('input_data', models.JSONField(help_text='AIに送信したプロンプトとパラメータ', verbose_name='入力データ')),
                ('output_data', models.JSONField(help_text='AIから受信した応答', verbose_name='出力データ')),
                ('tokens_used', models.IntegerField(blank=True, null=True, verbose_name='使用トークン数')),
                ('cost', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='コスト（USD）')),
                ('response_time', models.FloatField(blank=True, null=True, verbose_name='応答時間（秒）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='実行日時')),
                ('human_rating', models.IntegerField(blank=True, help_text='1-5の評価（5が最高）', null=True, verbose_name='人間評価')),
                ('is_accurate', models.BooleanField(blank=True, help_text='AIの応答が正確だったか', null=True, verbose_name='正確性')),
                ('feedback', models.TextField(blank=True, help_text='AIの応答に対する人間のフィードバック', verbose_name='フィードバック')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_logs', to='billing_management.servicelocation', verbose_name='事業所')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_logs', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'AI応答ログ',
                'verbose_name_plural': 'AI応答ログ',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'model'], name='billing_man_provide_add744_idx'), models.Index(fields=['task_type'], name='billing_man_task_ty_a7fe5e_idx'), models.Index(fields=['created_at'], name='billing_man_created_1ca93b_idx'), models.Index(fields=['location'], name='billing_man_locatio_23b84a_idx')],
            },
        ),
    ]
