# Generated by Django 5.2.9 on 2025-12-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workrecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='workrecord',
            name='service_type',
            field=models.CharField(default='Hodei', max_length=10, verbose_name='サービス種別（放デイ/ミニリハなど）'),
        ),
        migrations.AlterUniqueTogether(
            name='workrecord',
            unique_together={('staff', 'work_date', 'service_type')},
        ),
    ]
