# Generated by Django 5.2.9 on 2025-12-09 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_management', '0002_alter_workrecord_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_code', models.CharField(max_length=20, unique=True, verbose_name='利用者コード')),
                ('full_name', models.CharField(max_length=100, verbose_name='氏名')),
            ],
            options={
                'verbose_name': '利用者',
                'verbose_name_plural': '利用者',
            },
        ),
        migrations.CreateModel(
            name='FTESufficientStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_month', models.DateField(verbose_name='計算対象月（月初日）')),
                ('total_fte', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='全職員の合計FTE')),
                ('specialist_fte', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='専門職の合計FTE')),
                ('required_fte_for_kasan', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='加算に必要なFTE')),
                ('is_kasan_sufficient', models.BooleanField(default=False, verbose_name='加算充足ステータス')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing_management.servicelocation', verbose_name='事業所')),
            ],
            options={
                'verbose_name': '加算充足ステータス',
                'verbose_name_plural': '加算充足ステータス',
                'unique_together': {('location', 'calculation_month')},
            },
        ),
        migrations.CreateModel(
            name='ProgressAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateField(verbose_name='評価日')),
                ('progress_score', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='成長スコア（1-5段階）')),
                ('specialist_comment', models.TextField(blank=True, verbose_name='専門職コメント（PT/OT等）')),
                ('nlp_keyword_tags', models.CharField(blank=True, max_length=255, verbose_name='NLP抽出キーワード')),
                ('sentiment_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='感情スコア')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing_management.client', verbose_name='利用者')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing_management.staff', verbose_name='担当職員')),
            ],
            options={
                'verbose_name': '進捗・評価',
                'verbose_name_plural': '進捗・評価',
                'unique_together': {('client', 'assessment_date')},
            },
        ),
    ]
