# Generated by Django 5.2.9 on 2025-12-28 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_management', '0002_aiprompt_ailog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='バッジ名')),
                ('description', models.TextField(verbose_name='説明')),
                ('category', models.CharField(choices=[('attendance', '出席'), ('signature', '電子サイン'), ('activity', '活動'), ('growth', '成長'), ('special', '特別')], max_length=20, verbose_name='カテゴリ')),
                ('icon', models.CharField(default='🏆', max_length=50, verbose_name='アイコン')),
                ('condition_type', models.CharField(max_length=50, verbose_name='条件タイプ')),
                ('condition_value', models.IntegerField(verbose_name='条件値')),
                ('display_order', models.IntegerField(default=0, verbose_name='表示順')),
            ],
            options={
                'verbose_name': 'バッジ',
                'verbose_name_plural': 'バッジ',
                'db_table': 'badges',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('activity_type', models.CharField(max_length=50, verbose_name='活動種別')),
                ('description', models.TextField(verbose_name='活動内容')),
                ('staff_comment', models.TextField(blank=True, verbose_name='職員コメント')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='activity_photos/', verbose_name='活動写真')),
                ('is_published', models.BooleanField(default=True, verbose_name='保護者に公開')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='billing_management.client', verbose_name='利用者')),
            ],
            options={
                'verbose_name': '活動記録',
                'verbose_name_plural': '活動記録',
                'db_table': 'activity_logs',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0, verbose_name='合計ポイント')),
                ('attendance_points', models.IntegerField(default=0, verbose_name='出席ポイント')),
                ('activity_points', models.IntegerField(default=0, verbose_name='活動ポイント')),
                ('growth_points', models.IntegerField(default=0, verbose_name='成長ポイント')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='billing_management.client', verbose_name='利用者')),
            ],
            options={
                'verbose_name': 'ポイント',
                'verbose_name_plural': 'ポイント',
                'db_table': 'client_points',
            },
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='件名')),
                ('body', models.TextField(verbose_name='本文')),
                ('message_type', models.CharField(choices=[('individual', '個別'), ('bulk', '一斉配信')], default='individual', max_length=20, verbose_name='メッセージタイプ')),
                ('status', models.CharField(choices=[('draft', '下書き'), ('sent', '送信済み'), ('failed', '送信失敗')], default='draft', max_length=20, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='送信日時')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='email_attachments/', verbose_name='添付ファイル')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_emails', to=settings.AUTH_USER_MODEL, verbose_name='送信者')),
            ],
            options={
                'verbose_name': 'メールメッセージ',
                'verbose_name_plural': 'メールメッセージ',
                'db_table': 'email_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuardianUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
                ('relationship', models.CharField(default='保護者', max_length=50, verbose_name='続柄')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='メール通知を受け取る')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='最終ログイン日時')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='billing_management.client', verbose_name='利用者')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_profile', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '保護者ユーザー',
                'verbose_name_plural': '保護者ユーザー',
                'db_table': 'guardian_users',
            },
        ),
        migrations.CreateModel(
            name='ClientBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='獲得日時')),
                ('notification_sent', models.BooleanField(default=False, verbose_name='通知送信済み')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_by', to='billing_management.badge', verbose_name='バッジ')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to='billing_management.client', verbose_name='利用者')),
            ],
            options={
                'verbose_name': '獲得バッジ',
                'verbose_name_plural': '獲得バッジ',
                'db_table': 'client_badges',
                'ordering': ['-earned_at'],
                'unique_together': {('client', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='EmailRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian_email', models.EmailField(max_length=254, verbose_name='保護者メールアドレス')),
                ('read_status', models.CharField(choices=[('unread', '未読'), ('read', '既読')], default='unread', max_length=20, verbose_name='既読ステータス')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='既読日時')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_emails', to='billing_management.client', verbose_name='受信者（利用者）')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='billing_management.emailmessage', verbose_name='メッセージ')),
            ],
            options={
                'verbose_name': 'メール受信者',
                'verbose_name_plural': 'メール受信者',
                'db_table': 'email_recipients',
                'unique_together': {('message', 'client')},
            },
        ),
    ]
