# Generated by Django 5.2.9 on 2025-12-09 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_management', '0003_client_ftesufficientstatus_progressassessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPeerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField(auto_now_add=True, verbose_name='評価日')),
                ('cooperation_score', models.IntegerField(verbose_name='協調性スコア（1-5）')),
                ('review_comment', models.TextField(blank=True, verbose_name='コメント')),
                ('reviewed_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='billing_management.staff', verbose_name='評価対象者')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to='billing_management.staff', verbose_name='評価者')),
            ],
            options={
                'verbose_name': '職員相互評価',
                'verbose_name_plural': '職員相互評価',
                'unique_together': {('reviewer', 'reviewed_staff', 'review_date')},
            },
        ),
    ]
