# Generated by Django 5.2.9 on 2025-12-11 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_management', '0005_progressassessment_analysis_result_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='生年月日'),
        ),
        migrations.AddField(
            model_name='client',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='保護者氏名'),
        ),
        migrations.AddField(
            model_name='client',
            name='long_term_goal',
            field=models.TextField(blank=True, verbose_name='長期目標'),
        ),
        migrations.AddField(
            model_name='client',
            name='recipient_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='受給者番号'),
        ),
        migrations.AddField(
            model_name='client',
            name='short_term_goal',
            field=models.TextField(blank=True, verbose_name='短期目標'),
        ),
        migrations.AddField(
            model_name='client',
            name='support_content',
            field=models.TextField(blank=True, verbose_name='支援内容'),
        ),
    ]
