# Generated by Django 5.2.9 on 2025-12-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_management', '0006_client_birth_date_client_guardian_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressassessment',
            name='ai_feedback',
            field=models.TextField(blank=True, verbose_name='AI改善提案'),
        ),
        migrations.AddField(
            model_name='progressassessment',
            name='analyzed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='AI分析日時'),
        ),
        migrations.AddField(
            model_name='progressassessment',
            name='record_quality_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='記録の質スコア (1-5)'),
        ),
    ]
