# Generated by Django 5.2.9 on 2025-12-12 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_management', '0007_progressassessment_ai_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='guardian_signature',
            field=models.TextField(blank=True, verbose_name='保護者署名データ'),
        ),
        migrations.AddField(
            model_name='client',
            name='signature_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='署名日時'),
        ),
    ]
