# Generated by Django 5.2.9 on 2025-12-13 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_management', '0008_client_guardian_signature_client_signature_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='guardian_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='保護者メールアドレス'),
        ),
    ]
