# Generated by Django 5.2.9 on 2025-12-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatutoryDocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例: 事故・ヒヤリハット報告書', max_length=100, unique=True, verbose_name='書類名')),
                ('description', models.TextField(blank=True, help_text='書類の目的や用途の説明', verbose_name='説明')),
                ('frontend_path', models.CharField(help_text='例: /accident-reports', max_length=200, verbose_name='フロントエンドURLパス')),
                ('icon_name', models.CharField(blank=True, help_text='UI表示用のアイコン名（例: ReportProblem）', max_length=50, verbose_name='アイコン名')),
                ('order', models.PositiveIntegerField(default=0, help_text='ハブ画面での表示順序（小さい順）', verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, help_text='無効にするとハブ画面に表示されなくなります', verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '法定書類種別',
                'verbose_name_plural': '法定書類種別',
                'ordering': ['order', 'name'],
            },
        ),
    ]
