"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEYは環境変数から必ず設定すること（デフォルト値はセキュリティリスク）
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    # 開発環境のみのフォールバック（本番環境では必ず環境変数を設定）
    if os.environ.get('APP_ENV') == 'PROD':
        raise ValueError('⚠️ SECRET_KEY環境変数が設定されていません！')
    SECRET_KEY = 'django-insecure-dev-only-do-not-use-in-production'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '127.0.0.1,localhost,8000-ibqa2709bn7qa8oaxxs5m-62dc687b.manus-asia.computer').split(',')


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'billing_management',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# デフォルトはSQLite（開発環境用）
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# 本番環境ではPostgreSQLを使用（環境変数DATABASE_URLから取得）
if 'DATABASE_URL' in os.environ:
    DATABASES['default'] = dj_database_url.parse(os.environ['DATABASE_URL'], conn_max_age=600)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Custom User Model (マルチテナント対応)
AUTH_USER_MODEL = 'billing_management.CustomUser'


# Reactのデフォルトの稼働ポートを指定
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # Vite/React のデフォルトポート
]

# 開発中は CSRF 保護を一時的に緩める設定 (本番では厳格化が必要です)
# ReactからのPOSTリクエストを許可するため
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "https://8000-ibqa2709bn7qa8oaxxs5m-62dc687b.manus-asia.computer",
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 常勤換算の基準時間設定
# 週40時間を常勤の基準とする
FULL_TIME_HOURS_PER_WEEK = 40

# CSRFエラー対策: 公開URLのオリジンを信頼する
# 環境変数RENDER_EXTERNAL_URLがあればそれを使用
if 'RENDER_EXTERNAL_URL' in os.environ:
    CSRF_TRUSTED_ORIGINS = [os.environ['RENDER_EXTERNAL_URL']]
else:
    CSRF_TRUSTED_ORIGINS = ['http://localhost:5173', 'https://8000-ibqa2709bn7qa8oaxxs5m-62dc687b.manus-asia.computer']

# ====================================================================
# 🔒 セキュリティ設定強化
# ====================================================================

# HTTPS/SSL設定（本番環境のみ）
if not DEBUG:
    # HTTPS強制リダイレクト
    SECURE_SSL_REDIRECT = True
    
    # HSTS（HTTP Strict Transport Security）
    SECURE_HSTS_SECONDS = 31536000  # 1年間
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # セキュアCookie設定
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # X-Content-Type-Options
    SECURE_CONTENT_TYPE_NOSNIFF = True
    
    # X-Frame-Options
    X_FRAME_OPTIONS = 'DENY'
    
    # X-XSS-Protection
    SECURE_BROWSER_XSS_FILTER = True

# セッションセキュリティ
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_AGE = 3600  # 1時間でセッション期限切れ

# CSRFセキュリティ
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'

# パスワードバリデーション強化
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 12,  # 最小12文字
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ====================================================================
# 🔒 セキュリティログ設定
# ====================================================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django.security': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}
