# Generated by Django 5.2.9 on 2025-12-28 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing_management', '0003_badge_activitylog_clientpoints_emailmessage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('accident', '事故'), ('hiyari_hatto', 'ヒヤリハット')], max_length=20, verbose_name='区分')),
                ('occurred_at', models.DateTimeField(verbose_name='発生日時')),
                ('location_detail', models.CharField(help_text='例: 居室内、廊下、トイレ、食堂、送迎車内', max_length=255, verbose_name='発生場所（詳細）')),
                ('service_type', models.CharField(choices=[('houmon_kaigo', '訪問介護'), ('houmon_kango', '訪問看護'), ('day_service', '通所介護（デイサービス）'), ('day_care', '通所リハビリテーション（デイケア）'), ('short_stay', '短期入所生活介護（ショートステイ）'), ('group_home', '認知症対応型共同生活介護（グループホーム）'), ('houdehi', '放課後等デイサービス'), ('jihatsu', '児童発達支援'), ('other', 'その他')], max_length=50, verbose_name='サービス種別')),
                ('incident_description', models.TextField(help_text='発生時の状況を時系列で客観的に記載', verbose_name='事実経過')),
                ('client_state', models.TextField(blank=True, help_text='発生時・発生後の利用者の状態', verbose_name='利用者の状態')),
                ('damage_status', models.TextField(blank=True, help_text='怪我の有無、程度、部位など', verbose_name='被害の状況')),
                ('initial_response', models.TextField(blank=True, help_text='発生直後に行った対応', verbose_name='初期対応')),
                ('family_contact_log', models.TextField(blank=True, help_text='連絡日時、連絡先、連絡内容', verbose_name='家族等への連絡状況')),
                ('medical_response', models.TextField(blank=True, help_text='受診の有無、医療機関名、診断内容', verbose_name='医療機関への対応')),
                ('ai_generated_overview', models.TextField(blank=True, verbose_name='事故の状況（AI生成）')),
                ('ai_generated_cause_analysis', models.TextField(blank=True, verbose_name='原因分析（AI生成）')),
                ('ai_generated_prevention_plan', models.TextField(blank=True, verbose_name='再発防止策（AI生成）')),
                ('is_government_report_needed', models.BooleanField(default=False, verbose_name='行政報告要否')),
                ('government_report_reason', models.TextField(blank=True, verbose_name='行政報告要否の判定理由')),
                ('status', models.CharField(choices=[('draft', '作成中'), ('pending_review', '承認待ち'), ('approved', '承認済み')], default='draft', max_length=20, verbose_name='ステータス')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='承認日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_accidents', to=settings.AUTH_USER_MODEL, verbose_name='承認者')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accident_reports', to='billing_management.client', verbose_name='利用者')),
                ('involved_staff', models.ManyToManyField(blank=True, related_name='involved_accidents', to='billing_management.staff', verbose_name='関係職員')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accident_reports', to='billing_management.servicelocation', verbose_name='発生場所（事業所）')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_accidents', to=settings.AUTH_USER_MODEL, verbose_name='報告者（起案者）')),
            ],
            options={
                'verbose_name': '事故・ヒヤリハット報告書',
                'verbose_name_plural': '事故・ヒヤリハット報告書',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='AccidentAuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', '作成'), ('viewed', '閲覧'), ('updated', '更新'), ('ai_generated', 'AI生成実行'), ('submitted_for_review', '承認申請'), ('approved', '承認'), ('rejected', '差戻し'), ('pdf_generated', 'PDF出力'), ('pdf_downloaded', 'PDFダウンロード')], max_length=50, verbose_name='操作内容')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='操作日時')),
                ('details', models.JSONField(blank=True, help_text='操作に関する追加情報（例: 変更前後の値）', null=True, verbose_name='操作詳細')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IPアドレス')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='操作ユーザー')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trails', to='accident_reporting.accidentreport', verbose_name='関連報告書')),
            ],
            options={
                'verbose_name': '監査証跡',
                'verbose_name_plural': '監査証跡',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AccidentReportVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(verbose_name='バージョン番号')),
                ('snapshot_data', models.JSONField(help_text='その時点の報告書データの完全なスナップショット（JSON形式）', verbose_name='スナップショットデータ')),
                ('edited_at', models.DateTimeField(auto_now_add=True, verbose_name='編集日時')),
                ('change_summary', models.TextField(blank=True, help_text='このバージョンでの主な変更点', verbose_name='変更概要')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='編集者')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='accident_reporting.accidentreport', verbose_name='関連報告書')),
            ],
            options={
                'verbose_name': '報告書バージョン',
                'verbose_name_plural': '報告書バージョン',
                'ordering': ['-version_number'],
                'unique_together': {('report', 'version_number')},
            },
        ),
    ]
